feat: модуль статистики
Siberian797/java-explore-with-me pull request #3
Opened 2023-07-02 21:54 UTC by Siberian797

feat: модуль статистики

2023-07-04 19:34 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохо, но давай доработаем местами

2023-07-04 19:34 UTC, krylov-sergey-sergeevich commented on ewm-stats/ewm-stats-client/pom.xml
> +        <dependency>
а нельзя ниже две зависимости при помощи spring-boot-web подключить?

2023-07-04 19:34 UTC, krylov-sergey-sergeevich commented on ewm-stats/ewm-stats-dto/pom.xml
> +            <version>5.3.23</version>
зачем версия?

2023-07-04 19:34 UTC, krylov-sergey-sergeevich commented on ewm-stats/ewm-stats-dto/pom.xml
> +            <artifactId>jackson-annotations</artifactId>
зачем?

2023-07-04 19:34 UTC, krylov-sergey-sergeevich commented on ewm-stats/ewm-stats-dto/pom.xml
> +            <artifactId>jakarta.validation-api</artifactId>
spring validation чем то не устраивает?

2023-07-04 19:34 UTC, krylov-sergey-sergeevich commented on ewm-stats/ewm-stats-dto/src/main/java/ru/practicum/stats/dto/EndpointHitRequestDto.java
> +public class EndpointHitRequestDto implements Serializable {
модификаторы доступа?

2023-07-04 19:34 UTC, krylov-sergey-sergeevich commented on ewm-stats/ewm-stats-dto/src/main/java/ru/practicum/stats/dto/EndpointHitResponseDto.java
> +public class EndpointHitResponseDto implements Serializable {
модификаторы доступа?

2023-07-04 19:34 UTC, krylov-sergey-sergeevich commented on ewm-stats/ewm-stats-server/pom.xml
> +        <dependency>
две бд подключается, нам обе нужны?

2023-07-04 19:34 UTC, krylov-sergey-sergeevich commented on ewm-stats/ewm-stats-server/src/main/resources/schema.sql
Можно как у тебя, но как второе мнение скину пример как еще можно было бы устроить хранение:
```
CREATE TABLE IF NOT EXISTS apps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(150) NOT NULL,
  CONSTRAINT pk_aps PRIMARY KEY (id),
  CONSTRAINT UQ_APPS_NAME UNIQUE(name)
);

CREATE TABLE IF NOT EXISTS endpoint_hit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  app_id BIGINT NOT NULL,
  uri VARCHAR(2048),
  ip VARCHAR(15) NOT NULL,
  ts TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CONSTRAINT pk_endpoint_hit PRIMARY KEY (id),
  CONSTRAINT FK_ENDPOINT_HIT_ON_APP FOREIGN KEY (app_id) REFERENCES apps (id)
);
```

2023-07-04 23:27 UTC, Siberian797 commented on ewm-stats/ewm-stats-dto/src/main/java/ru/practicum/stats/dto/EndpointHitResponseDto.java
> +public class EndpointHitResponseDto implements Serializable {
Поля автоматически становятся private при использовании @Value

2023-07-04 23:31 UTC, Siberian797 commented on ewm-stats/ewm-stats-dto/pom.xml
> +            <artifactId>jackson-annotations</artifactId>
Для использования @JsonFormat

2023-07-04 23:37 UTC, Siberian797 commented on ewm-stats/ewm-stats-server/pom.xml
> +        <dependency>
да, локально в спринге работает h2, а в докере работает postgres

2023-07-05 05:25 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-07-05 06:28 UTC, merged