feat: основной функционал
Siberian797/java-explore-with-me pull request #4
Opened 2023-07-15 23:35 UTC by Siberian797

feat: основной функционал

2023-07-19 14:27 UTC, krylov-sergey-sergeevich requested changes
Привет, есть что доработать, давай обсудим и улучшим

2023-07-19 14:27 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/main/java/ru/practicum/main/category/service/CategoryServiceImpl.java
> +    public CategoryDto readCategory(Long categoryId) {
read своеобразный нейминг мжт get?

2023-07-19 14:27 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/main/java/ru/practicum/main/compilation/dto/CompilationDto.java
> +    transient List<EventShortDto> events;
А тут точно нужно слово transient?

2023-07-19 14:27 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/main/java/ru/practicum/main/compilation/dto/NewCompilationDto.java
> +    Set<Long> events;
Обычно более сложные поля ниже идут по коду сущности

2023-07-19 14:27 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/main/java/ru/practicum/main/compilation/repository/CompilationRepository.java
> +    @EntityGraph(value = Compilation.GRAPH_EVENT, type = EntityGraph.EntityGraphType.LOAD)
Лайк)

2023-07-19 14:27 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/main/java/ru/practicum/main/compilation/service/CompilationServiceImpl.java
> +        if (Objects.isNull(newCompilationDto)) {
А не прикольнее писать == null? или есть тайный смысл в таком подходе

2023-07-19 14:27 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/main/java/ru/practicum/main/compilation/service/CompilationServiceImpl.java
> +        return events.stream().map(event -> EventMapper.toShortDto(event, CategoryMapper.toDto(event.getCategory()),
давай на строки побьем хотя бы, а то сливается в глазах

2023-07-19 14:27 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/main/java/ru/practicum/main/event/dto/EventShortDto.java
> +    transient CategoryDto category;
к transient  вопросики есть

2023-07-19 14:27 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/main/java/ru/practicum/main/event/dto/NewEventDto.java
> +    String title;
чтоб совсем красиво title должен рядом с полем описание лежать чтобы легче было сущность понимать

2023-07-19 14:27 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/main/java/ru/practicum/main/event/dto/NewEventDto.java
> +public class NewEventDto {
@JsonIgnoreProperties(ignoreUnknown = true) - можно докинуть

2023-07-19 14:27 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/main/java/ru/practicum/main/event/service/EventServiceImpl.java
> +    private final StatsClient statsClient = new StatsClient("http://stats-server:9090", new RestTemplateBuilder());
хардкод, нельзя ли из переменных приложения получить?

2023-07-19 14:27 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/main/java/ru/practicum/main/utils/CommonUtils.java
> +public class CommonUtils {
Так это утилита или тут бизнес код идет и структурный, как то не совсем красиво выходит и репозиторий и клиент

2023-07-19 18:05 UTC, Siberian797 commented on ewm-main-service/src/main/java/ru/practicum/main/category/service/CategoryServiceImpl.java
> +    public CategoryDto readCategory(Long categoryId) {
Там вообще идея была в разделении create, read, update и delete)
Но согласен, get практичнее

2023-07-19 19:04 UTC, Siberian797 commented on ewm-main-service/src/main/java/ru/practicum/main/event/dto/NewEventDto.java
> +public class NewEventDto {
Докинул. Пошли плавающие баги - то один сервис ошибки кидает, то другой. Убрал

2023-07-19 22:30 UTC, Siberian797 commented on ewm-stats/ewm-stats-client/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
Сделал, пошли ошибки в тестах. Вернул обратно

2023-07-20 19:24 UTC, krylov-sergey-sergeevich commented on ewm-stats/ewm-stats-client/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
А понимание есть почему ошибки? Тк в целом не очень понятно почему такое должно быть

2023-07-20 19:24 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/main/java/ru/practicum/main/event/dto/NewEventDto.java
> +public class NewEventDto {
А понимание есть почему ошибки? Тк в целом не очень понятно почему такое должно быть

2023-07-20 19:25 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-07-20 19:51 UTC, merged